-- FIELD move FX catalog. Add a named move here instead of editing projectiles.lua.
-- Loaded via require("fx_catalog") (shimmed in field/init.lua from fx/fx_catalog.lua).

local Catalog = {}

Catalog.TYPE_COLORS = {
  NORMAL = { 0.86, 0.86, 0.78 },
  FIRE = { 1.00, 0.34, 0.12 },
  WATER = { 0.20, 0.58, 1.00 },
  ELECTRIC = { 1.00, 0.88, 0.18 },
  GRASS = { 0.30, 0.82, 0.28 },
  ICE = { 0.52, 0.90, 1.00 },
  FIGHTING = { 0.78, 0.28, 0.22 },
  POISON = { 0.66, 0.30, 0.78 },
  GROUND = { 0.72, 0.52, 0.28 },
  FLYING = { 0.62, 0.72, 0.96 },
  PSYCHIC = { 0.92, 0.34, 0.82 },
  BUG = { 0.66, 0.78, 0.20 },
  ROCK = { 0.66, 0.56, 0.34 },
  GHOST = { 0.52, 0.36, 0.72 },
  DRAGON = { 0.45, 0.36, 0.88 },
  DARK = { 0.40, 0.32, 0.28 },
  STEEL = { 0.72, 0.74, 0.80 },
  FAIRY = { 0.94, 0.58, 0.78 },
}

-- Gen 1 type-split marks these physical; they still fly, so FIELD / REACT
-- treat them as specials (no close-the-gap, no melee counter from across
-- the pad). Contact punches stay physical via MOVE_FX style = "contact".
Catalog.PROJECTILE_SPECIAL = {
  SWIFT = true,
  GUST = true,
  NIGHT_SHADE = true,
  TRI_ATTACK = true,
  BONEMERANG = true,
  ROCK_THROW = true,
}

-- Named move overrides (style on effect/move; glitz tunes the paint).
Catalog.MOVE_FX = {
  HYPER_BEAM = { style = "beam", glitz = "hyper", duration = 0.72 },
  SOLARBEAM = { style = "beam", glitz = "thick", duration = 0.44, color = { 0.72, 1.00, 0.42 } },
  ICE_BEAM = {
    style = "beam",
    glitz = "icebolt",
    duration = 0.36,
    color = { 0.48, 0.86, 1.00 },
  },
  AURORA_BEAM = { style = "beam", glitz = "frost" },
  PSYBEAM = {
    style = "beam",
    glitz = "psy",
    duration = 0.52,
    color = { 0.96, 0.42, 0.88 },
  },
  THUNDERBOLT = { style = "beam", glitz = "bolt", duration = 0.36 },
  THUNDERSHOCK = { style = "beam", glitz = "bolt", duration = 0.30 },
  THUNDER = { style = "bolt", duration = 0.42 },
  FLAMETHROWER = { style = "stream", glitz = "flame", duration = 0.52 },
  FIRE_BLAST = { style = "blast", glitz = "flame", radius = 26, duration = 0.64 },
  EMBER = { style = "ember", glitz = "flame", duration = 0.54, arc = 13 },
  FIRE_SPIN = { style = "spiral", glitz = "flame", duration = 0.52 },
  HYDRO_PUMP = { style = "stream", glitz = "bubble", duration = 0.46 },
  WATER_GUN = { style = "stream", glitz = "jet", duration = 0.52 },
  BUBBLEBEAM = { style = "stream", glitz = "bubble", duration = 0.46 },
  BUBBLE_BEAM = { style = "stream", glitz = "bubble", duration = 0.46 },
  BUBBLE = { style = "orb", glitz = "bubble", arc = 12 },
  SURF = {
    style = "surf",
    glitz = "tide",
    duration = 0.68,
    radius = 18,
    color = { 0.18, 0.62, 0.98 },
  },
  BLIZZARD = { style = "area", glitz = "frost", radius = 22 },
  PSYCHIC = {
    style = "aura",
    glitz = "psy",
    duration = 0.62,
    color = { 0.92, 0.34, 0.82 },
  },
  PSYCHIC_M = {
    style = "aura",
    glitz = "psy",
    duration = 0.62,
    color = { 0.92, 0.34, 0.82 },
  },
  CONFUSION = {
    style = "aura",
    glitz = "confuse",
    duration = 0.50,
    color = { 0.86, 0.48, 0.96 },
  },
  DREAM_EATER = { style = "drain", glitz = "psy", duration = 0.52 },
  MEGA_DRAIN = { style = "drain", glitz = "leaf", duration = 0.48 },
  GIGA_DRAIN = { style = "drain", glitz = "leaf", duration = 0.52 },
  ABSORB = { style = "drain", glitz = "leaf", duration = 0.42 },
  RAZOR_LEAF = {
    style = "razor",
    glitz = "blade",
    duration = 0.68,
    color = { 0.42, 0.88, 0.22 },
  },
  PETAL_DANCE = { style = "multi", glitz = "leaf", duration = 0.44 },
  VINE_WHIP = { style = "stream", glitz = "leaf" },
  LEECH_SEED = {
    style = "seed",
    glitz = "leaf",
    duration = 0.58,
    color = { 0.28, 0.72, 0.24 },
  },
  SLUDGE = { style = "orb", glitz = "blob", arc = 9 },
  SLUDGE_BOMB = { style = "orb", glitz = "blob", arc = 12 },
  ACID = { style = "stream", glitz = "blob" },
  SMOG = { style = "area", glitz = "blob", radius = 16 },
  TOXIC = { style = "status", glitz = "blob", duration = 0.55 },
  SUPERSONIC = {
    style = "sonic",
    glitz = "ring",
    duration = 0.62,
    color = { 0.70, 0.88, 1.00 },
  },
  CONFUSE_RAY = {
    style = "ray",
    glitz = "confuse",
    duration = 0.48,
    color = { 0.72, 0.32, 0.98 },
  },
  EARTHQUAKE = { style = "area", glitz = "quake", radius = 22, duration = 0.62 },
  FISSURE = { style = "area", glitz = "quake", radius = 18 },
  ROCK_SLIDE = { style = "slide", glitz = "rock", duration = 0.72, radius = 16 },
  ROCK_THROW = { style = "rock", glitz = "rock", duration = 0.58, arc = 22 },
  EXPLOSION = { style = "area", glitz = "burst", radius = 28, duration = 0.55 },
  SELFDESTRUCT = { style = "area", glitz = "burst", radius = 26, duration = 0.52 },
  SWIFT = {
    style = "swift",
    glitz = "star",
    duration = 0.52,
    color = { 1.00, 0.92, 0.42 },
  },
  DOUBLE_TEAM = {
    style = "clones",
    glitz = "afterimage",
    duration = 0.82,
    color = { 0.70, 0.78, 0.94 },
  },
  TRI_ATTACK = { style = "multi", glitz = "tri", duration = 0.40 },
  NIGHT_SHADE = {
    style = "shadow",
    glitz = "shade",
    duration = 0.52,
    color = { 0.18, 0.08, 0.26 },
  },
  LICK = { style = "contact", glitz = "ghost" },
  DRAGON_RAGE = { style = "stream", glitz = "dragon" },
  HORN_DRILL = { style = "beam", glitz = "pierce" },
  FLASH = { style = "area", glitz = "flash", radius = 18, duration = 0.32 },
  SAND_ATTACK = {
    style = "sand",
    glitz = "grit",
    duration = 0.58,
    color = { 0.82, 0.62, 0.32 },
  },
  SANDATTACK = {
    style = "sand",
    glitz = "grit",
    duration = 0.58,
    color = { 0.82, 0.62, 0.32 },
  },
  RECOVER = { style = "heal" },
  SOFTBOILED = { style = "heal" },
  REST = { style = "heal" },
  -- Physical contact signatures (still land at the foe).
  SLASH = { style = "contact", glitz = "slash" },
  CUT = { style = "contact", glitz = "slash" },
  FURY_SWIPES = { style = "contact", glitz = "slash" },
  FURY_ATTACK = { style = "contact", glitz = "pierce" },
  HORN_ATTACK = { style = "contact", glitz = "pierce" },
  PECK = { style = "contact", glitz = "pierce" },
  DRILL_PECK = { style = "contact", glitz = "pierce" },
  BITE = { style = "contact", glitz = "bite" },
  CRUNCH = { style = "contact", glitz = "bite" },
  BODY_SLAM = { style = "contact", glitz = "impact" },
  TAKE_DOWN = { style = "contact", glitz = "impact" },
  DOUBLE_EDGE = { style = "contact", glitz = "impact" },
  TACKLE = { style = "contact", glitz = "impact" },
  STRENGTH = { style = "contact", glitz = "impact" },
  MEGA_PUNCH = { style = "contact", glitz = "impact" },
  MEGA_KICK = { style = "contact", glitz = "impact" },
  QUICK_ATTACK = { style = "contact", glitz = "dash", duration = 0.34 },
  EXTREMESPEED = { style = "contact", glitz = "dash", duration = 0.40 },
  EXTREME_SPEED = { style = "contact", glitz = "dash", duration = 0.40 },
  -- Weak / early physicals: still get a readable contact signature.
  POUND = { style = "contact", glitz = "slap" },
  SCRATCH = { style = "contact", glitz = "slash" },
  DOUBLE_SLAP = { style = "contact", glitz = "slap" },
  DOUBLESLAP = { style = "contact", glitz = "slap" },
  COMET_PUNCH = { style = "contact", glitz = "punch" },
  KARATE_CHOP = { style = "contact", glitz = "slash" },
  DOUBLE_KICK = { style = "contact", glitz = "kick" },
  ROLLING_KICK = { style = "contact", glitz = "kick" },
  JUMP_KICK = { style = "contact", glitz = "kick" },
  HI_JUMP_KICK = { style = "contact", glitz = "kick" },
  HIGH_JUMP_KICK = { style = "contact", glitz = "kick" },
  LOW_KICK = { style = "contact", glitz = "kick" },
  STOMP = { style = "contact", glitz = "impact" },
  HEADBUTT = { style = "contact", glitz = "impact" },
  WRAP = { style = "contact", glitz = "wrap" },
  BIND = { style = "contact", glitz = "wrap" },
  CONSTRICT = { style = "contact", glitz = "wrap" },
  POISON_STING = { style = "contact", glitz = "sting" },
  TWINEEDLE = { style = "contact", glitz = "sting" },
  PIN_MISSILE = { style = "contact", glitz = "sting" },
  SPIKE_CANNON = { style = "contact", glitz = "pierce" },
  LEECH_LIFE = { style = "contact", glitz = "bite" },
  PAY_DAY = { style = "contact", glitz = "coin" },
  RAGE = { style = "contact", glitz = "impact" },
  SUPER_FANG = { style = "contact", glitz = "bite" },
  WING_ATTACK = { style = "contact", glitz = "wing" },
  GUST = {
    style = "gust",
    glitz = "wind",
    duration = 0.56,
    color = { 0.70, 0.84, 1.00 },
  },
  FLY = { style = "contact", glitz = "wing" },
  SKY_ATTACK = { style = "contact", glitz = "wing" },
  BARRAGE = { style = "contact", glitz = "impact" },
  BONE_CLUB = { style = "contact", glitz = "impact" },
  BONEMERANG = { style = "orb", glitz = "rock", arc = 14 },
  VICEGRIP = { style = "contact", glitz = "pinch" },
  VICE_GRIP = { style = "contact", glitz = "pinch" },
  VISE_GRIP = { style = "contact", glitz = "pinch" },
  CLAMP = { style = "contact", glitz = "pinch" },
  CRABHAMMER = { style = "contact", glitz = "impact" },
  WATERFALL = { style = "stream", glitz = "bubble" },
  SEISMIC_TOSS = { style = "contact", glitz = "toss", duration = 1.08 },
  FIRE_PUNCH = {
    style = "contact",
    glitz = "firepunch",
    duration = 0.42,
    color = { 1.00, 0.34, 0.12 },
  },
  ICE_PUNCH = {
    style = "contact",
    glitz = "icepunch",
    duration = 0.42,
    color = { 0.52, 0.90, 1.00 },
  },
  THUNDERPUNCH = {
    style = "contact",
    glitz = "thunderpunch",
    duration = 0.42,
    color = { 1.00, 0.88, 0.18 },
  },
  THUNDER_PUNCH = {
    style = "contact",
    glitz = "thunderpunch",
    duration = 0.42,
    color = { 1.00, 0.88, 0.18 },
  },
  DIZZY_PUNCH = { style = "contact", glitz = "punch" },
  HYPER_FANG = { style = "contact", glitz = "bite" },
  THRASH = { style = "contact", glitz = "impact" },
  STRUGGLE = { style = "contact", glitz = "impact" },
  SLAM = { style = "contact", glitz = "impact" },
  SKULL_BASH = { style = "contact", glitz = "impact" },
  COUNTER = { style = "contact", glitz = "impact" },
  SUBMISSION = { style = "contact", glitz = "impact" },
}

Catalog.TYPE_STYLE = {
  FIRE = { style = "stream", glitz = "flame" },
  WATER = { style = "orb", glitz = "bubble" },
  ELECTRIC = { style = "beam", glitz = "bolt" },
  ICE = { style = "beam", glitz = "frost" },
  PSYCHIC = { style = "spiral", glitz = "psy" },
  GHOST = { style = "beam", glitz = "ghost" },
  GRASS = { style = "orb", glitz = "leaf" },
  POISON = { style = "orb", glitz = "blob" },
  DRAGON = { style = "stream", glitz = "dragon" },
  GROUND = { style = "area", glitz = "quake", radius = 18 },
  ROCK = { style = "orb", glitz = "rock", arc = 14 },
  BUG = { style = "orb", glitz = "leaf" },
  FLYING = { style = "gust", glitz = "wind" },
  FIGHTING = { style = "contact", glitz = "impact" },
  NORMAL = { style = "orb", glitz = "star" },
}

Catalog.TYPE_CONTACT = {
  FIRE = "flame",
  WATER = "bubble",
  ELECTRIC = "bolt",
  ICE = "frost",
  POISON = "blob",
  FIGHTING = "impact",
  FLYING = "wing",
  BUG = "slash",
  GHOST = "ghost",
  STEEL = "slash",
  ROCK = "impact",
  GROUND = "impact",
  NORMAL = "slash",
  DRAGON = "slash",
  PSYCHIC = "psy",
  GRASS = "leaf",
}

return Catalog
